### ISSUE TITLE
Failed in downloading the used data

### ISSUE THREAD

**Issue by jind11** [thunlp/SememePSO-Attack#1]
Hi, I tried downloading the processed data with the substitute candidates from US, however, it always failed in the middle of downloading process since it is too large. Could you provide another approach to download them such as Google Drive? Thanks!

**Comment by yangalan123** [comment]
Thanks for the feedback. We will post the Google drive links very soon. Please allow 1-2 days for data migration.

**Comment by yangalan123** [comment]
Sorry, I cannot contact the data manager in this project and I am also aboard. I will continue to contact him. If I have any news, I will let you know.

**Comment by yangalan123** [comment]
Sorry for the late reply, I plan to upload these data files this weekend. In case you are rushing some deadlines, you can just reproduce our pretrained and pre-computed files following the instructions on the README file in each dataset directory. If you come across any problem in this process, you can write it here and we will take a look. Thanks!

**Comment by yangalan123** [comment]
I have uploaded the data to Google Drive in the recent commit. Please pull to get the latest links. If you have any further problems, please reply in this issue.

**Comment by jind11** [comment]
Thank you so much!
