### ISSUE TITLE
About the code of the evaluation part

### ISSUE THREAD

**Issue by milumilum** [thunlp/SememePSO-Attack#5]
Hi, could you please pull up the code of the evaluation part? I am also doing relevant experiments, but the sentence complexity is quite different from your results, so I make this request and I want to learn from your code. 
thanks.

**Comment by yangalan123** [comment]
Hi! Thanks for your interest. I am one of the main maintainers of this project. I am a bit confused about your problem. By "sentence complexity" do you mean "perplexity" (PPL)? For the "perplexity", we simply use GPT-2 to help us compute PPL. Can you tell me how you compute your "sentence complexity" and how you compare your results with us?
