### ISSUE TITLE
delemmatization

### ISSUE THREAD

**Issue by dp0d** [thunlp/SememePSO-Attack#6]
Hi, thank you for provide the code! May I ask you that how you guys do the delemmatization in the code of IMDB dataset?

**Comment by zangy17** [comment]
We build a dictionary of the prototype words and their inflections occurred in IMDB dataset. Then we can exert the same inflections on the substitutions.

**Comment by dp0d** [comment]
oo……, In the code, I only found the operation that using prototype words to find their candidates rather than doing the delematization. Could you please inform me the exact steps?  I'd appreaciate it if you can update the code.
![image](https://user-images.githubusercontent.com/54127793/138559423-b37b9b8e-1840-4630-95e3-f682fed3a962.png)

**Comment by wenkfjsf** [comment]
有人成功复现了吗

**Comment by yangalan123** [comment]
Hi all,

Thanks for all your follow-ups on this issue and sorry for the late responses as all main authors have graduated and have not worked in this direction recently. We can guarantee that our experiments are **replicable** ( “可复现的" in Mandarin). There are already community-built toolkits that have successfully replicated our experiments, and improved our code quality and running efficiency by a lot: [TextAttack](https://github.com/QData/TextAttack) (EMNLP 2020 Demo, ~3k stars), and [OpenAttack](https://github.com/thunlp/OpenAttack) (ACL 2021 Demo, ~600 stars). So we encourage you to check the latest improved version there. This repo is currently under archival mode so the response would be significantly delayed and no major maintenance will happen in the foreseeable future. Thanks for your interest in this work and we encourage you to try the aforementioned toolkits and ask questions there. 

Best,
Chenghao
